### PR TITLE
Ignore data

### PR DESCRIPTION
**Pull request by MattyD797**
For preventing the uploading of unzipped files into the repo

### CODE REVIEW

**Comment by MattyD797** [comment]
So I really don't like unzipping...zipping...unzipping etc. So I used git large file storage for this data. I haven't used it before so I am glad it works. It works like a pointer to a different repository (...in a way) but just for the data. This way when someone clones or pulls it will just reference the link and pull the data from there.

**Comment by MattyD797** [comment]
Take note... make a new branch by merging main to new branch if pull request has not been accepted :)

**Comment by peterregier** [comment]
Major improvement in data storage!

**Review by peterregier — APPROVED** [review]
Data uploaded to respository, no more zips!

**Pull request merged**
